### ISSUE TITLE
UnderscoreNamingStrategy

### ISSUE THREAD

**Issue by lxregistry** [symfony/demo#1043]
after update to the symfony 4.3.8 this deprecation appear:
Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.

**Comment by stof** [comment]
That's not after updating Symfony. that's after updating the ORM.

**Comment by abdounikarim** [comment]
Hello, 

You can remove this message by customizing the doctrine.yaml configuration : 
replace `naming_strategy: doctrine.orm.naming_strategy.underscore`
by `naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware`

Cheers 😉

**Comment by vpArth** [comment]
@abdounikarim, I got error:

> The service "doctrine.orm.default_configuration" has a dependency on a non-existent service "doctrine.orm.naming_strategy.underscore_number_aware"

I have a deprecation warning, but no replacement service yet

Fixed with manual service redefine:
```yaml
    doctrine.orm.naming_strategy.underscore:
        class: Doctrine\ORM\Mapping\UnderscoreNamingStrategy
        arguments:
            $numberAware: true
```
