### ISSUE TITLE
Running in GitHub Codespaces

### ISSUE THREAD

**Issue by GromNaN** [symfony/demo#1542]
[GitHub Codespaces](https://github.com/features/codespaces) is a good solution to run and try modifying the application without installing anything the desktop. Part of the support was added by https://github.com/symfony/demo/pull/1369

But it doesn't  work anymore, we get the following message when starting a codespace.
> This codespace is currently running in recovery mode due to a configuration error. Please review the creation logs, update your dev container configuration as needed, and run the "Rebuild Container" command to rectify.

What we need to achieve with codespace:

- [ ] No error on start
- [ ] PHP installed with required extensions
- [ ] Composer packages installed
- [ ] Composer script run
- [ ] Server started (HTTP and HTTPS)
- [ ] Server port exposed
- [ ] Bonus: PHP extensions enabled in VScode
- [ ] Bonus: CI that ensure this doesn't break

**Comment by maxgrundnig** [comment]
I am working on this for SymfonyHackday

**Comment by maxgrundnig** [comment]
PR #1544 fixes the crash when starting a Codespace.

But there is another issue in Codespace: The Router generates absolute URLs with the port number included, which doesn't work in Codespace. I am not that familiar wit the Routing component, maybe somebody else can take a look at it?

**Comment by GromNaN** [comment]
> But there is another issue in Codespace: The Router generates absolute URLs with the port number included, which doesn't work in Codespace. I am not that familiar wit the Routing component, maybe somebody else can take a look at it?

It's to be due to the proxy provided by Codespace. This can be solved by setting one the [trusted proxies](https://symfony.com/doc/current/deployment/proxies.html):
```
framework:
    # shortcut for private IP address ranges of your proxy
    trusted_proxies: 'private_ranges'
    # trust *all* "X-Forwarded-*" headers
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
```

I'm not sure what would be the best for this project:
- adding the setting to the config, at risk of having people duplicating this configuration without knowing about the security issue they can have,
- or [setting environment variables in devcontainer.json](https://code.visualstudio.com/remote/advancedcontainers/environment-variables), so the configuration is scoped to the context of execution, but is more [complex to modify](https://docs.github.com/en/codespaces/developing-in-a-codespace/rebuilding-the-container-in-a-codespace) once the the container is running.

After that, there is still an issue with CSRF protection.
