### ISSUE TITLE
security.yml does not contain valid YAML

### ISSUE THREAD

**Issue by JamiePill** [symfony/demo#699]
```
 [Symfony\Component\Config\Exception\FileLoaderLoadException]
The file "C:\xampp\htdocs\loginpage\app/config\security.yml" does not contain
valid YAML in C:\xampp\htdocs\loginpage\app/config\security.yml (which is
being imported from "C:\xampp\htdocs\loginpage\app/config\config.yml").
```

```yaml
# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity: 
                class: AppBundle:User 
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/            
            security: false

        main:
            anonymous: ~
                form_login:
                    login_path: login
                    check_path: login
```

**Comment by javiereguiluz** [comment]
@JamiePill you have a YAML formatting issue here: 

```yaml
        main:
            anonymous: ~
                form_login:
                    login_path: login
                    check_path: login
```

It should be like this:

```yaml
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
```

If that doesn't fix the problem, please reopen the issue. Thanks!
