### ISSUE TITLE
App\Controller service registration question

### ISSUE THREAD

**Issue by mmarton** [symfony/demo#901]
In the current sercices.yaml file:

```yaml
services:
 ...
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
...
```

as the comment sais:
> controllers are imported separately to make sure services can be injected

Shouldn't they then excluded from the import section before?
Would it make any difference?
